#!/bin/sh
set -e -u -x

# Check environment

fail() {
    echo 1>&2 "$1"
    echo 1>&2 "Usage: $(basename "$0") [install|uninstall]"
    exit 255
}

if [ "$#" -lt 1 ]; then
    fail "Invalid number of arguments."
fi

if [ "$(id -u)" -ne 0 ]; then
    fail "Impossible to execute this script without root privileges."
fi

# Run installer

case "$1" in
    install)
        export $(curl --location "https://github.com/timonier/version-lister/raw/generated/just-containers/s6-overlay/latest" | xargs)
        curl --location "${S6_OVERLAY_RELEASE}" | tar --directory / --extract --gzip
        ;;

    uninstall)
        fail "Impossible to remove s6-overlay"
        ;;

    *)
        fail "Argument \"$1\" is invalid."
        ;;
esac
