#!/bin/sh
set -e -u -x

# Check environment

fail() {
    echo 1>&2 "$1"
    echo 1>&2 "Usage: $(basename "$0") [install|uninstall]"
    exit 255
}

if [ "$#" -lt 1 ]; then
    fail "Invalid number of arguments."
fi

# Run installer

INSTALL_DIRECTORY="${INSTALL_DIRECTORY:-/usr/sbin}"

case "$1" in
    install)
        mkdir -p "${INSTALL_DIRECTORY}"
        export $(curl --location "https://github.com/timonier/version-lister/raw/generated/yelp/dumb-init/latest" | xargs)
        curl --location --output "${INSTALL_DIRECTORY}"/dumb-init "${DUMB_INIT_RELEASE}"
        chmod +x "${INSTALL_DIRECTORY}"/dumb-init
        ;;

    uninstall)
        rm -f "${INSTALL_DIRECTORY}"/dumb-init
        ;;

    *)
        fail "Argument \"$1\" is invalid."
        ;;
esac
