#!/bin/sh
set -ex

# Check environment

fail() {
    echo 1>&2 "$1"
    echo 1>&2 "Usage: $(basename "$0") [install|uninstall]"
    exit 1
}

if [ "$#" -lt 1 ] ; then
    fail "Invalid number of arguments."
fi

if [ "$(id -u)" -ne 0 ] ; then
    fail "Impossible to prepare the system without root privileges."
fi

if [ "$(uname)" != "Linux" ] ; then
    fail "Impossible to prepare another operating system than Linux."
fi

# Run installer

INSTALL_DIRECTORY="${INSTALL_DIRECTORY:-/usr/local/sbin}"

case "$1" in
    install )
        export $(curl --location "https://github.com/timonier/version-lister/raw/generated/timonier/syslog-stdout/latest" | xargs)
        curl --location "https://github.com/timonier/syslog-stdout/releases/download/v${SYSLOG_STDOUT_VERSION}/syslog-stdout.tar.gz" | tar --directory /usr/sbin --extract --gzip
        chmod +x "${INSTALL_DIRECTORY}/syslog-stdout"
    ;;

    uninstall )
        rm -f "${INSTALL_DIRECTORY}/syslog-stdout"
    ;;

    * )
        fail "Argument \"$1\" is invalid."
esac
