#!/bin/bash
set -e -u -x

# Check environment

_fail() {
    echo 1>&2 "$1"
    echo 1>&2 "Usage: $(basename "$0") [install|uninstall]"
    exit 255
}

if [ "$#" -lt 1 ]; then
    _fail "Invalid number of arguments."
fi

# Run installer

INSTALL_DIRECTORY="${INSTALL_DIRECTORY:-/usr/sbin}"

case "$1" in
    install)
        mkdir -p "${INSTALL_DIRECTORY}"
        export $(curl --location "https://gitlab.com/timonier/version-lister/raw/generated/jwilder/dockerize/latest" | xargs)
        curl --location "${DOCKERIZE_RELEASE}" | tar --directory "${TMPDIR:-/tmp}" --extract --gzip
        mv ${TMPDIR:-/tmp}/dockerize "${INSTALL_DIRECTORY}"/dockerize
        chmod +x "${INSTALL_DIRECTORY}"/dockerize
        ;;

    uninstall)
        rm -f "${INSTALL_DIRECTORY}"/dockerize
        ;;

    *)
        _fail "Argument \"$1\" is invalid."
        ;;
esac
