#!/bin/sh

# Check current user

if [ $(id -u) -ne 0 ] ; then
    echo "Impossible to continue without root privileges." 1>&2
    exit 1
fi

# Configure locale

if [ -n "${LANG}" ] && [ -n "${LANGUAGE}" ] && which localedef > /dev/null ; then
    localedef -i ${LANGUAGE} -f UTF-8 ${LANG} > /dev/null 2> /dev/null
fi

# Run command

gosu ${USER:-root} "$@"
